
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    volumes:
      - .:/app 
    depends_on:
      - db 
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=stackoverflow_db
      - POSTGRES_PORT=5432
      - JWT_SECRET=KOL-MIKAELOV
    env_file:
      - .env

  db:
    image: postgres:14-alpine 
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD="mypassword"
      - POSTGRES_DB=stackoverflow_db
      - POSTGRES_HOST_AUTH_METHOD=trust 
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 

volumes:
  postgres-data:
